version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models:/app/models
    environment:
      - VOSK_MODEL_PATH=/app/models/vosk-model-small-en-us-0.15
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend/web
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend 